### ISSUE TITLE
Define the project vision, goals and general use cases

### ISSUE THREAD

**Issue by sehucke** [dlemper/garbanzo#7]
OK, let's do this! :-) My suggestions:

- **Project vision:**
Garbanzo aims to be a personal cookbook app that makes it easy to follow recipes, to adopt them, to store them for later use and to share them privately with others.

- **Project goals:**
  - Build a user-centric app to support the user in the key actions related to recipe handling.
  - Make it easy to involve others.
  - Create an app that is free and open-source.
  - Help to retain the user's control over his data.

There are many recipe apps out there. But they do all have their drawbacks - some more, some less.
1. They store your recipes "somewhere in the cloud" with no easy / automatic way to get your data under control.
2. They are closed source.
3. They show you ads.
4. They are missing a holistic approach, e.g. they only let you manage recipes but do not support you in all the related tasks. I think of missing or minimalist grocery lists, small instruction texts, no variants ("How did I modify the recipe last time? It was great!") ... And in particular the social element of cooking: What about preparing a meal with a bunch of friends? What about support for that? ("I'll bring the chicken. John prepares the salad... Who was the one to bake the pie?! Has someone a pen to write it down? I liked the pie Jane made last year, but this time put much more berries in it!")

Now feel free to discuss. :-)

**Comment by dlemper** [comment]
Could you please put this into the readme.md?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sehucke** [comment]
Sure. I put it in here for discussion. Sooo... If there are no remarks... Excellent. :-)

Will put it into readme.md tomorrow.

Am 21. August 2018 23:58:40 MESZ schrieb Daniel Lemper <notifications@github.com>:

**Comment by sehucke** [comment]
Closed with https://github.com/dlemper/garbanzo/commit/7acae7e2f10b692590a4957a380b2be289b003dc

**Comment by sehucke** [comment]
Closed with https://github.com/dlemper/garbanzo/commit/7acae7e2f10b692590a4957a380b2be289b003dc
